/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanciamentoRouteImport } from './routes/financiamento'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClientesAprovadosRouteImport } from './routes/clientes-aprovados'
import { Route as AvalieSeuUsadoRouteImport } from './routes/avalie-seu-usado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculoSlugRouteImport } from './routes/veiculo.$slug'
import { Route as EstoqueSlugRouteImport } from './routes/estoque.$slug'

const FinanciamentoRoute = FinanciamentoRouteImport.update({
  id: '/financiamento',
  path: '/financiamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesAprovadosRoute = ClientesAprovadosRouteImport.update({
  id: '/clientes-aprovados',
  path: '/clientes-aprovados',
  getParentRoute: () => rootRouteImport,
} as any)
const AvalieSeuUsadoRoute = AvalieSeuUsadoRouteImport.update({
  id: '/avalie-seu-usado',
  path: '/avalie-seu-usado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculoSlugRoute = VeiculoSlugRouteImport.update({
  id: '/veiculo/$slug',
  path: '/veiculo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueSlugRoute = EstoqueSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EstoqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avalie-seu-usado': typeof AvalieSeuUsadoRoute
  '/clientes-aprovados': typeof ClientesAprovadosRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financiamento': typeof FinanciamentoRoute
  '/estoque/$slug': typeof EstoqueSlugRoute
  '/veiculo/$slug': typeof VeiculoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avalie-seu-usado': typeof AvalieSeuUsadoRoute
  '/clientes-aprovados': typeof ClientesAprovadosRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financiamento': typeof FinanciamentoRoute
  '/estoque/$slug': typeof EstoqueSlugRoute
  '/veiculo/$slug': typeof VeiculoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avalie-seu-usado': typeof AvalieSeuUsadoRoute
  '/clientes-aprovados': typeof ClientesAprovadosRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/financiamento': typeof FinanciamentoRoute
  '/estoque/$slug': typeof EstoqueSlugRoute
  '/veiculo/$slug': typeof VeiculoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avalie-seu-usado'
    | '/clientes-aprovados'
    | '/contato'
    | '/estoque'
    | '/financiamento'
    | '/estoque/$slug'
    | '/veiculo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avalie-seu-usado'
    | '/clientes-aprovados'
    | '/contato'
    | '/estoque'
    | '/financiamento'
    | '/estoque/$slug'
    | '/veiculo/$slug'
  id:
    | '__root__'
    | '/'
    | '/avalie-seu-usado'
    | '/clientes-aprovados'
    | '/contato'
    | '/estoque'
    | '/financiamento'
    | '/estoque/$slug'
    | '/veiculo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvalieSeuUsadoRoute: typeof AvalieSeuUsadoRoute
  ClientesAprovadosRoute: typeof ClientesAprovadosRoute
  ContatoRoute: typeof ContatoRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  FinanciamentoRoute: typeof FinanciamentoRoute
  VeiculoSlugRoute: typeof VeiculoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/financiamento': {
      id: '/financiamento'
      path: '/financiamento'
      fullPath: '/financiamento'
      preLoaderRoute: typeof FinanciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes-aprovados': {
      id: '/clientes-aprovados'
      path: '/clientes-aprovados'
      fullPath: '/clientes-aprovados'
      preLoaderRoute: typeof ClientesAprovadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avalie-seu-usado': {
      id: '/avalie-seu-usado'
      path: '/avalie-seu-usado'
      fullPath: '/avalie-seu-usado'
      preLoaderRoute: typeof AvalieSeuUsadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculo/$slug': {
      id: '/veiculo/$slug'
      path: '/veiculo/$slug'
      fullPath: '/veiculo/$slug'
      preLoaderRoute: typeof VeiculoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/$slug': {
      id: '/estoque/$slug'
      path: '/$slug'
      fullPath: '/estoque/$slug'
      preLoaderRoute: typeof EstoqueSlugRouteImport
      parentRoute: typeof EstoqueRoute
    }
  }
}

interface EstoqueRouteChildren {
  EstoqueSlugRoute: typeof EstoqueSlugRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueSlugRoute: EstoqueSlugRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvalieSeuUsadoRoute: AvalieSeuUsadoRoute,
  ClientesAprovadosRoute: ClientesAprovadosRoute,
  ContatoRoute: ContatoRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  FinanciamentoRoute: FinanciamentoRoute,
  VeiculoSlugRoute: VeiculoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
